define([], function () {
  return {
    PropertyPaneDescription: 'Shows one suggestion. The id is read from the address (?forslag=<id>).',
    DisplayGroupName: 'Display',
    SourceGroupName: 'Data source',
    ShowMapLabel: 'Map',
    ShowCommentsLabel: 'Comments',
    ShowRelatedLabel: 'Related suggestions',
    ShowEvaluationLabel: 'Case worker panel (case workers only)',
    FixedIdLabel: 'Fixed suggestion id',
    FixedIdDescription: 'Used when the address has no ?forslag=<id>, e.g. to feature one suggestion.',
    SiteUrlFieldLabel: 'KomInn site address',
    SiteUrlFieldDescription: 'Leave empty to use the current site.',

    Loading: 'Loading suggestion …',
    NoIdText: 'No suggestion selected. Open the page from a suggestion list, or set a fixed id in the property pane.',
    NotFoundText: 'The suggestion was not found. It may be deleted, or you lack access.',
    LoadErrorTitle: 'Could not load the suggestion.',
    TypeSuggestion: 'Suggestion',
    TypeSuccess: 'Success story',
    TypePast: 'Done before',
    ChallengesTitle: 'Challenges',
    SolutionTitle: 'Suggested solution',
    UsefulForOthersTitle: 'Useful for others',
    GoalsTitle: 'Sustainability goals',
    Like: 'Like',
    Liked: 'Liked',
    CommentsShort: 'comments',
    DoThisToo: 'We want to do this too',
    DoThisTooHint: 'Opens the form pre-filled from this suggestion.',
    CopyLink: 'Copy link',
    LinkCopied: 'Link copied',
    DetailsTitle: 'Details',
    AmountLabel: 'Amount',
    StatusLabel: 'Status',
    CaseWorkerStatusLabel: 'Case status',
    CaseWorkerLabel: 'Case worker',
    SubmitterLabel: 'Submitted by',
    EmailLabel: 'Email',
    ManagerLabel: 'Manager',
    CompetitionRefLabel: 'Competition',
    MapTitle: 'Location',

    RelatedTitle: 'Related suggestions',
    RelatedBefore: 'Builds on',
    RelatedAfter: 'Has inspired',

    CommentsTitle: 'Comments',
    CommentsEmpty: 'No comments yet. Be the first.',
    CommentsLoadError: 'Could not load comments.',
    CommentLabel: 'Write a comment',
    CommentSend: 'Send',
    CommentSending: 'Sending …',

    CaseWorkerTitle: 'Case handling',
    CaseWorkerHint: 'Only visible to the Case workers group.',
    SaveStatus: 'Save status',
    StatusSaved: 'Status saved.',
    AverageTitle: 'Average of all evaluations',
    AverageEmpty: 'No evaluations yet.',
    AverageCount: 'Number of evaluations',
    MyEvaluationTitle: 'Your evaluation (1–5)',
    ScoreFeasibility: 'Feasibility',
    ScoreEmission: 'Emission reduction potential',
    ScoreDistribution: 'Distribution potential',
    ScoreInnovation: 'Degree of innovation',
    MoreActorsLabel: 'Multiple actors involved',
    LawRequirementsLabel: 'Legal requirements',
    EvaluationCommentLabel: 'Short comment',
    SaveEvaluation: 'Save evaluation',
    EvaluationSaved: 'Evaluation saved.'
  };
});
