define([], function () {
  return {
    PropertyPaneDescription: 'Viser ett forslag. Id-en hentes fra adressen (?forslag=<id>).',
    DisplayGroupName: 'Visning',
    SourceGroupName: 'Datakilde',
    ShowMapLabel: 'Kart',
    ShowCommentsLabel: 'Kommentarer',
    ShowRelatedLabel: 'Relaterte forslag',
    ShowEvaluationLabel: 'Saksbehandlerpanel (kun for saksbehandlere)',
    FixedIdLabel: 'Fast forslag-id',
    FixedIdDescription: 'Brukes når adressen ikke har ?forslag=<id>, f.eks. for å fremheve ett forslag.',
    SiteUrlFieldLabel: 'Adresse til KomInn-området',
    SiteUrlFieldDescription: 'La stå tom for å bruke området webdelen står på.',

    Loading: 'Laster forslaget …',
    NoIdText: 'Ingen forslag er valgt. Åpne siden fra en forslagsliste, eller angi en fast forslag-id i egenskapsruten.',
    NotFoundText: 'Fant ikke forslaget. Det kan være slettet, eller du mangler tilgang.',
    LoadErrorTitle: 'Kunne ikke hente forslaget.',
    TypeSuggestion: 'Forslag',
    TypeSuccess: 'Suksesshistorie',
    TypePast: 'Gjort tidligere',
    ChallengesTitle: 'Utfordringer',
    SolutionTitle: 'Forslag til løsning',
    UsefulForOthersTitle: 'Nyttig for andre',
    GoalsTitle: 'Bærekraftsmål',
    Like: 'Lik',
    Liked: 'Liker',
    CommentsShort: 'kommentarer',
    DoThisToo: 'Dette vil vi også gjøre',
    DoThisTooHint: 'Åpner skjemaet ferdig utfylt fra dette forslaget.',
    CopyLink: 'Kopier lenke',
    LinkCopied: 'Lenken er kopiert',
    DetailsTitle: 'Detaljer',
    AmountLabel: 'Søkt sum',
    StatusLabel: 'Status',
    CaseWorkerStatusLabel: 'Saksbehandling',
    CaseWorkerLabel: 'Saksbehandler',
    SubmitterLabel: 'Sendt inn av',
    EmailLabel: 'E-post',
    ManagerLabel: 'Nærmeste leder',
    CompetitionRefLabel: 'Konkurranse',
    MapTitle: 'Sted',

    RelatedTitle: 'Relaterte forslag',
    RelatedBefore: 'Bygger på',
    RelatedAfter: 'Har inspirert',

    CommentsTitle: 'Kommentarer',
    CommentsEmpty: 'Ingen kommentarer ennå. Bli den første.',
    CommentsLoadError: 'Kunne ikke hente kommentarene.',
    CommentLabel: 'Skriv en kommentar',
    CommentSend: 'Send',
    CommentSending: 'Sender …',

    CaseWorkerTitle: 'Saksbehandling',
    CaseWorkerHint: 'Kun synlig for gruppen Saksbehandlere.',
    SaveStatus: 'Lagre status',
    StatusSaved: 'Status er lagret.',
    AverageTitle: 'Snitt av alle vurderinger',
    AverageEmpty: 'Ingen vurderinger ennå.',
    AverageCount: 'Antall vurderinger',
    MyEvaluationTitle: 'Din vurdering (1–5)',
    ScoreFeasibility: 'Gjennomførbarhet',
    ScoreEmission: 'Potensial for utslippsreduksjon',
    ScoreDistribution: 'Spredningspotensial',
    ScoreInnovation: 'Innovasjonsgrad',
    MoreActorsLabel: 'Flere aktører involvert',
    LawRequirementsLabel: 'Lovkrav',
    EvaluationCommentLabel: 'Kort kommentar',
    SaveEvaluation: 'Lagre vurdering',
    EvaluationSaved: 'Vurderingen er lagret.'
  };
});
