define([], function () {
  return {
    PropertyPaneDescription: 'Choose which suggestions to show, how, and where to load them from.',
    ContentGroupName: 'Content',
    LayoutGroupName: 'Display',
    SourceGroupName: 'Data source',
    ModeFieldLabel: 'Show',
    ModePublished: 'Published suggestions',
    ModePromoted: 'Promoted suggestions',
    ModeSuccess: 'Success stories',
    ModeMonthly: 'Suggestion of the month',
    ModeMine: 'My suggestions',
    PeriodFieldLabel: 'Period',
    PeriodAll: 'All',
    PeriodThisYear: 'This year',
    PeriodLast12Months: 'Last 12 months',
    TopFieldLabel: 'Suggestions per page',
    EmptyTextFieldLabel: 'Text when the list is empty',
    LayoutFieldLabel: 'Layout',
    LayoutCards: 'Card grid',
    LayoutCarousel: 'Carousel',
    LayoutCompact: 'Compact list',
    ShowFiltersLabel: 'Filter on focus areas and tags',
    ShowSortingLabel: 'Let users change sorting',
    SiteUrlFieldLabel: 'KomInn site address',
    SiteUrlFieldDescription: 'Leave empty to use the current site. Fill in to show suggestions from another site, for example on the intranet.',
    TitlePlaceholder: 'Enter a title',
    DefaultAriaLabel: 'Suggestions',
    DefaultEmptyText: 'No suggestions found.',
    NoFilterResults: 'No suggestions match the filters.',
    Loading: 'Loading suggestions …',
    LoadError: 'Could not load suggestions.',
    Likes: 'likes',
    Comments: 'comments',
    FilterFocusAreas: 'Focus area',
    FilterTags: 'Tags',
    FilterAll: 'All',
    FilterClear: 'Clear filters',
    SortLabel: 'Sort by',
    SortLikes: 'Most liked',
    SortComments: 'Most commented',
    SortCreated: 'Newest first',
    ShowMore: 'Show more',
    Previous: 'Previous',
    Next: 'Next'
  };
});
