define([], function () {
  return {
    PropertyPaneDescription: 'Velg hvilke forslag listen skal vise, hvordan, og hvor de hentes fra.',
    ContentGroupName: 'Innhold',
    LayoutGroupName: 'Visning',
    SourceGroupName: 'Datakilde',
    ModeFieldLabel: 'Vis',
    ModePublished: 'Publiserte forslag',
    ModePromoted: 'Promoterte forslag',
    ModeSuccess: 'Suksesshistorier',
    ModeMonthly: 'Månedens forslag',
    ModeMine: 'Mine forslag',
    PeriodFieldLabel: 'Periode',
    PeriodAll: 'Alle',
    PeriodThisYear: 'Inneværende år',
    PeriodLast12Months: 'Siste 12 måneder',
    TopFieldLabel: 'Antall forslag per side',
    EmptyTextFieldLabel: 'Tekst når listen er tom',
    LayoutFieldLabel: 'Oppsett',
    LayoutCards: 'Kort i rutenett',
    LayoutCarousel: 'Karusell',
    LayoutCompact: 'Kompakt liste',
    ShowFiltersLabel: 'Filter på innsatsområder og tags',
    ShowSortingLabel: 'Brukeren kan velge sortering',
    SiteUrlFieldLabel: 'Adresse til KomInn-området',
    SiteUrlFieldDescription: 'La stå tom for å bruke området webdelen står på. Fyll ut for å vise forslag fra et annet område, f.eks. på intranettet.',
    TitlePlaceholder: 'Skriv en tittel',
    DefaultAriaLabel: 'Forslag',
    DefaultEmptyText: 'Finner ingen forslag.',
    NoFilterResults: 'Ingen forslag passer filtrene.',
    Loading: 'Laster forslag …',
    LoadError: 'Kunne ikke hente forslag.',
    Likes: 'liker',
    Comments: 'kommentarer',
    FilterFocusAreas: 'Innsatsområde',
    FilterTags: 'Tags',
    FilterAll: 'Alle',
    FilterClear: 'Nullstill filter',
    SortLabel: 'Sortering',
    SortLikes: 'Mest likt',
    SortComments: 'Mest kommentert',
    SortCreated: 'Nyeste først',
    ShowMore: 'Vis flere',
    Previous: 'Forrige',
    Next: 'Neste'
  };
});
