define([], function () {
  return {
    PropertyPaneDescription: 'Configure the new suggestion form.',
    TextsGroupName: 'Texts',
    SectionsGroupName: 'Visible fields',
    SourceGroupName: 'Data source',
    IntroTextLabel: 'Introduction',
    SuccessTextLabel: 'Text after submission',
    CompetitionRefLabel: 'Competition reference',
    CompetitionRefDescription: 'Stored on every suggestion submitted from this web part, e.g. CLIMATE2026.',
    ShowAmountLabel: 'Amount applied for',
    ShowChallengesLabel: 'Challenges',
    ShowSolutionLabel: 'Suggested solution',
    ShowUsefulForOthersLabel: 'Useful for others',
    ShowTagsLabel: 'Tags',
    ShowGoalsLabel: 'Sustainability goals',
    ShowImageLabel: 'Image',
    ShowLocationLabel: 'Location on map',
    ShowInspiredByLabel: 'Inspired by',
    SiteUrlFieldLabel: 'KomInn site address',
    SiteUrlFieldDescription: 'Leave empty to store suggestions on the current site.',

    Loading: 'Loading …',
    SelectPlaceholder: 'Select',
    NoResults: 'No results',
    SectionSuggestion: 'The suggestion',
    TitleLabel: 'Title',
    SummaryLabel: 'Description',
    SummaryHint: 'What do you want to do, and why?',
    AmountLabel: 'How much are you applying for?',
    AmountHint: 'Amount in NOK, no spaces.',
    ChallengesLabel: 'Which challenges does it solve?',
    ChallengesHint: 'Describe the problem with the current situation.',
    SolutionLabel: 'Suggested solution',
    UsefulForOthersLabel: 'How can others benefit?',
    FocusAreasLabel: 'Focus areas',
    TagsLabel: 'Tags',
    SectionGoals: 'Sustainability goals',
    GoalsHint: 'Select the goals this supports.',
    SectionMedia: 'Image and location',
    ImageLabel: 'Image',
    ImageDrop: 'Drop an image here, or click to choose',
    ImageBrowse: 'Choose image',
    ImageRemove: 'Remove image',
    ImageHint: 'JPG or PNG. The image is scaled down automatically.',
    LocationLabel: 'Location',
    LocationHint: 'Click the map to mark where this belongs.',
    LocationClear: 'Clear location',
    SectionInspiredBy: 'Inspired by',
    InspiredByHint: 'Is this based on something others did? Search for the suggestion.',
    InspiredByPlaceholder: 'Search suggestions',
    SectionPerson: 'About you',
    PersonHint: 'Taken from your profile. Correct anything that is wrong.',
    NameLabel: 'Name',
    EmailLabel: 'Email',
    DepartmentLabel: 'Department',
    TelephoneLabel: 'Phone',
    ManagerLabel: 'Manager',
    ManagerHint: 'Stored with the suggestion so your manager can be involved.',
    ConsentLabel: 'The suggestion becomes visible to everyone on the site once a case worker publishes it.',
    Submit: 'Submit suggestion',
    Submitting: 'Submitting …',
    Reset: 'Clear form',
    SubmitErrorTitle: 'The suggestion was not submitted.',
    ValidationRequired: 'Required',
    ValidationAmount: 'Enter a whole amount',
    ValidationEmail: 'Enter a valid email address',
    CopyTitle: 'We want to do this too.',
    CopyText: 'The form was filled in from',
    SuccessTitle: 'Thank you! The suggestion was submitted.',
    SuccessDefaultText: 'A case worker will review it and publish it when ready.',
    SuccessOpen: 'View suggestion',
    SuccessNew: 'Submit another suggestion'
  };
});
