declare interface INyttForslagWebPartStrings {
  PropertyPaneDescription: string;
  TextsGroupName: string;
  SectionsGroupName: string;
  SourceGroupName: string;
  IntroTextLabel: string;
  SuccessTextLabel: string;
  CompetitionRefLabel: string;
  CompetitionRefDescription: string;
  ShowAmountLabel: string;
  ShowChallengesLabel: string;
  ShowSolutionLabel: string;
  ShowUsefulForOthersLabel: string;
  ShowTagsLabel: string;
  ShowGoalsLabel: string;
  ShowImageLabel: string;
  ShowLocationLabel: string;
  ShowInspiredByLabel: string;
  SiteUrlFieldLabel: string;
  SiteUrlFieldDescription: string;

  Loading: string;
  SelectPlaceholder: string;
  NoResults: string;
  SectionSuggestion: string;
  TitleLabel: string;
  SummaryLabel: string;
  SummaryHint: string;
  AmountLabel: string;
  AmountHint: string;
  ChallengesLabel: string;
  ChallengesHint: string;
  SolutionLabel: string;
  UsefulForOthersLabel: string;
  FocusAreasLabel: string;
  TagsLabel: string;
  SectionGoals: string;
  GoalsHint: string;
  SectionMedia: string;
  ImageLabel: string;
  ImageDrop: string;
  ImageBrowse: string;
  ImageRemove: string;
  ImageHint: string;
  LocationLabel: string;
  LocationHint: string;
  LocationClear: string;
  SectionInspiredBy: string;
  InspiredByHint: string;
  InspiredByPlaceholder: string;
  SectionPerson: string;
  PersonHint: string;
  NameLabel: string;
  EmailLabel: string;
  DepartmentLabel: string;
  TelephoneLabel: string;
  ManagerLabel: string;
  ManagerHint: string;
  ConsentLabel: string;
  Submit: string;
  Submitting: string;
  Reset: string;
  SubmitErrorTitle: string;
  ValidationRequired: string;
  ValidationAmount: string;
  ValidationEmail: string;
  CopyTitle: string;
  CopyText: string;
  SuccessTitle: string;
  SuccessDefaultText: string;
  SuccessOpen: string;
  SuccessNew: string;
}

declare module 'NyttForslagWebPartStrings' {
  const strings: INyttForslagWebPartStrings;
  export = strings;
}
