define([], function () {
  return {
    PropertyPaneDescription: 'Tilpass skjemaet for nye forslag.',
    TextsGroupName: 'Tekster',
    SectionsGroupName: 'Felt som vises',
    SourceGroupName: 'Datakilde',
    IntroTextLabel: 'Innledningstekst',
    SuccessTextLabel: 'Tekst etter innsending',
    CompetitionRefLabel: 'Konkurransereferanse',
    CompetitionRefDescription: 'Lagres på alle forslag som sendes inn fra denne webdelen, f.eks. KLIMA2026.',
    ShowAmountLabel: 'Søkt sum',
    ShowChallengesLabel: 'Utfordringer',
    ShowSolutionLabel: 'Forslag til løsning',
    ShowUsefulForOthersLabel: 'Nyttig for andre',
    ShowTagsLabel: 'Tags',
    ShowGoalsLabel: 'Bærekraftsmål',
    ShowImageLabel: 'Bilde',
    ShowLocationLabel: 'Sted på kart',
    ShowInspiredByLabel: 'Inspirert av',
    SiteUrlFieldLabel: 'Adresse til KomInn-området',
    SiteUrlFieldDescription: 'La stå tom for å lagre forslag på området webdelen står på.',

    Loading: 'Laster …',
    SelectPlaceholder: 'Velg',
    NoResults: 'Ingen treff',
    SectionSuggestion: 'Forslaget',
    TitleLabel: 'Tittel',
    SummaryLabel: 'Beskrivelse av tiltaket',
    SummaryHint: 'Hva vil du gjøre, og hvorfor?',
    AmountLabel: 'Hvor mye søker du om?',
    AmountHint: 'Beløp i kroner, uten mellomrom.',
    ChallengesLabel: 'Hvilke utfordringer løser tiltaket?',
    ChallengesHint: 'Beskriv problemet dagens situasjon gir.',
    SolutionLabel: 'Forslag til løsning',
    UsefulForOthersLabel: 'Hvordan kan andre ha nytte av dette?',
    FocusAreasLabel: 'Innsatsområder',
    TagsLabel: 'Tags',
    SectionGoals: 'Bærekraftsmål',
    GoalsHint: 'Velg målene tiltaket støtter opp under.',
    SectionMedia: 'Bilde og sted',
    ImageLabel: 'Bilde',
    ImageDrop: 'Slipp et bilde her, eller klikk for å velge',
    ImageBrowse: 'Velg bilde',
    ImageRemove: 'Fjern bilde',
    ImageHint: 'JPG eller PNG. Bildet skaleres ned automatisk.',
    LocationLabel: 'Sted',
    LocationHint: 'Klikk i kartet for å markere hvor tiltaket hører til.',
    LocationClear: 'Fjern sted',
    SectionInspiredBy: 'Inspirert av',
    InspiredByHint: 'Bygger forslaget på noe andre har gjort? Søk opp forslaget.',
    InspiredByPlaceholder: 'Søk etter forslag',
    SectionPerson: 'Om deg',
    PersonHint: 'Hentet fra profilen din. Rett det som ikke stemmer.',
    NameLabel: 'Navn',
    EmailLabel: 'E-post',
    DepartmentLabel: 'Avdeling / virksomhet',
    TelephoneLabel: 'Telefon',
    ManagerLabel: 'Nærmeste leder',
    ManagerHint: 'Lagres sammen med forslaget slik at leder kan involveres.',
    ConsentLabel: 'Forslaget blir synlig for alle på området når det publiseres av en saksbehandler.',
    Submit: 'Send inn forslag',
    Submitting: 'Sender inn …',
    Reset: 'Tøm skjemaet',
    SubmitErrorTitle: 'Forslaget ble ikke sendt inn.',
    ValidationRequired: 'Må fylles ut',
    ValidationAmount: 'Skriv et beløp i hele kroner',
    ValidationEmail: 'Skriv en gyldig e-postadresse',
    CopyTitle: 'Dette vil vi også gjøre.',
    CopyText: 'Skjemaet er fylt ut fra forslaget',
    SuccessTitle: 'Takk! Forslaget er sendt inn.',
    SuccessDefaultText: 'En saksbehandler ser på forslaget og publiserer det når det er klart.',
    SuccessOpen: 'Se forslaget',
    SuccessNew: 'Send inn et nytt forslag'
  };
});
