define([], function () {
  return {
    PropertyPaneDescription: 'Overview for case workers. Only visible to the Case workers group.',
    DefaultFilterGroupName: 'Show by default',
    SourceGroupName: 'Data source',
    MaxItemsLabel: 'Maximum number of suggestions',
    SiteUrlFieldLabel: 'KomInn site address',
    SiteUrlFieldDescription: 'Leave empty to use the current site.',

    Loading: 'Loading …',
    NoAccessTitle: 'No access.',
    NoAccessText: 'This page is for members of the Case workers group. Contact the site owner if you need access.',
    LoadErrorTitle: 'Could not load suggestions.',
    CountsLabel: 'Count per case status',
    SearchLabel: 'Search',
    SearchPlaceholder: 'Title, submitter or department',
    AllStatuses: 'All statuses',
    MineOnly: 'Mine only',
    Refresh: 'Refresh',
    ShowingCount: 'Showing {0} of {1} suggestions',
    TableLabel: 'Suggestions to handle',
    ColTitle: 'Title',
    ColCreated: 'Submitted',
    ColSubmitter: 'Submitter',
    ColCaseWorkerStatus: 'Case status',
    ColStatus: 'Publishing',
    ColCaseWorker: 'Case worker',
    ColScore: 'Avg. score',
    ColLikes: 'Likes',
    ColActions: 'Actions',
    Handle: 'Handle',
    NoRows: 'No suggestions match the filters.',
    Unassigned: 'Unassigned',

    Close: 'Close',
    OpenSuggestion: 'Open suggestion',
    StatusLabel: 'Publishing',
    StatusHint: 'Published, Success and Promoted make the suggestion visible in lists.',
    CaseWorkerStatusLabel: 'Case status',
    CaseWorkerLabel: 'Case worker',
    AssignToMe: 'Assign to me',
    EvaluationTitle: 'Evaluations',
    EvaluationCount: 'Number of evaluations',
    NoEvaluations: 'No evaluations yet.',
    EvaluateHint: 'Your own evaluation is done on the suggestion page.',
    ScoreFeasibility: 'Feasibility',
    ScoreEmission: 'Emission reduction',
    ScoreDistribution: 'Distribution potential',
    ScoreInnovation: 'Degree of innovation',
    Save: 'Save',
    Cancel: 'Cancel'
  };
});
