define([], function () {
  return {
    PropertyPaneDescription: 'Oversikt for saksbehandlere. Kun synlig for gruppen Saksbehandlere.',
    DefaultFilterGroupName: 'Vis som standard',
    SourceGroupName: 'Datakilde',
    MaxItemsLabel: 'Maks antall forslag',
    SiteUrlFieldLabel: 'Adresse til KomInn-området',
    SiteUrlFieldDescription: 'La stå tom for å bruke området webdelen står på.',

    Loading: 'Laster …',
    NoAccessTitle: 'Ingen tilgang.',
    NoAccessText: 'Denne siden er for medlemmer av gruppen Saksbehandlere. Kontakt eieren av området om du skal ha tilgang.',
    LoadErrorTitle: 'Kunne ikke hente forslagene.',
    CountsLabel: 'Antall per saksbehandlerstatus',
    SearchLabel: 'Søk',
    SearchPlaceholder: 'Tittel, innsender eller avdeling',
    AllStatuses: 'Alle statuser',
    MineOnly: 'Kun mine',
    Refresh: 'Oppdater',
    ShowingCount: 'Viser {0} av {1} forslag',
    TableLabel: 'Forslag til behandling',
    ColTitle: 'Tittel',
    ColCreated: 'Sendt inn',
    ColSubmitter: 'Innsender',
    ColCaseWorkerStatus: 'Saksbehandling',
    ColStatus: 'Publisering',
    ColCaseWorker: 'Saksbehandler',
    ColScore: 'Snittscore',
    ColLikes: 'Liker',
    ColActions: 'Handlinger',
    Handle: 'Behandle',
    NoRows: 'Ingen forslag passer filtrene.',
    Unassigned: 'Ikke tildelt',

    Close: 'Lukk',
    OpenSuggestion: 'Åpne forslaget',
    StatusLabel: 'Publisering',
    StatusHint: 'Publisert, Suksess og Promotert gjør forslaget synlig i listene.',
    CaseWorkerStatusLabel: 'Saksbehandlerstatus',
    CaseWorkerLabel: 'Saksbehandler',
    AssignToMe: 'Tildel meg',
    EvaluationTitle: 'Vurderinger',
    EvaluationCount: 'Antall vurderinger',
    NoEvaluations: 'Ingen vurderinger ennå.',
    EvaluateHint: 'Egen vurdering gjøres på forslagssiden.',
    ScoreFeasibility: 'Gjennomførbarhet',
    ScoreEmission: 'Utslippsreduksjon',
    ScoreDistribution: 'Spredningspotensial',
    ScoreInnovation: 'Innovasjonsgrad',
    Save: 'Lagre',
    Cancel: 'Avbryt'
  };
});
